name: Testing
on: 
  push

jobs:
    jobConditional:
        env:
            SECRET_EXISTS: ${{ secrets.SECRET_EXISTS }}
        runs-on: ubuntu-latest
        if: ${{ github.env.SECRET_EXISTS != '' }}
        steps:
            - run: echo "This ran"
    stepConditional:
        runs-on: ubuntu-latest
        env:
            SECRET_EXISTS: ${{ secrets.SECRET_EXISTS }}
        steps:
            - run: echo "This ran"
              if: ${{ github.env.SECRET_EXISTS != '' }}